package com.gstbilling.app.navigation

object Routes {
    const val LOGIN = "auth/login"
    const val REGISTER = "auth/register"
    const val DASHBOARD = "dashboard"
    const val CUSTOMERS = "customers"
    const val ADD_CUSTOMER = "customers/add"
    const val EDIT_CUSTOMER = "customers/{customerId}/edit"
    const val CUSTOMER_LEDGER = "customers/{customerId}/ledger"
    const val PRODUCTS = "products"
    const val ADD_PRODUCT = "products/add"
    const val EDIT_PRODUCT = "products/{productId}/edit"
    const val PRODUCT_DETAIL = "products/{productId}/detail"
    const val STOCK_ADJUST = "products/{productId}/stock-adjust"
    const val WAREHOUSES = "warehouses"
    const val STOCK_TRANSFER = "stock-transfer"
    const val LOW_STOCK_ALERTS = "low-stock-alerts"
    const val PURCHASE_ORDERS = "purchase-orders"
    const val SUPPLIERS = "suppliers"
    const val CREATE_INVOICE = "billing/create"
    const val CREATE_INVOICE_WITH_CUSTOMER = "billing/create/{customerId}"
    const val INVOICES = "invoices"
    const val INVOICE_DETAIL = "invoices/{invoiceId}"
    const val EDIT_INVOICE = "invoices/{invoiceId}/edit"
    const val INVOICE_SHARE = "invoices/{invoiceId}/share"
    const val INVOICE_PREVIEW = "invoices/{invoiceId}/preview"
    const val BULK_INVOICES = "billing/bulk"
    const val STAFF = "staff"
    const val EDIT_PERMISSIONS = "staff/{userId}/permissions/{currentName}"
    const val REPORTS = "reports"
    const val CUSTOMER_REPORT = "reports/customers"
    const val PRODUCT_REPORT = "reports/products"
    const val PROFIT_LOSS = "reports/profit-loss"
    const val SETTINGS = "settings"
    const val PAYMENTS = "payments"
    const val RECORD_PAYMENT = "payments/record"
    const val RECORD_PAYMENT_FOR_INVOICE = "payments/record/{invoiceId}"
    const val UPI_PAYMENT = "payments/upi"
    const val PAYMENT_HISTORY = "payments/history"
    const val NOTIFICATIONS = "notifications"
    const val BATCH_EXPIRY = "batch_expiry"
    const val BARCODE_SCANNER = "barcode_scanner"
    const val CUSTOMER_GROUPS = "customer_groups"
    const val PAYMENT_REMINDERS = "payment_reminders"
    const val INVENTORY_DASHBOARD = "inventory_dashboard"
    const val STOCK_MOVEMENTS = "stock_movements"
    const val DATA_IMPORT = "settings/import"
    const val EXPORT_DATA = "settings/export"
    const val BUSINESS_LIST = "businesses"
    const val BUSINESS_PROFILE = "settings/business-profile"
    const val TAX_SETTINGS = "settings/tax"
    const val INVOICE_TEMPLATE = "settings/invoice-template"
    const val PAYMENT_METHODS = "settings/payment-methods"
    const val PRINT_SETTINGS = "settings/print"
    const val SYNC_DATA = "settings/sync"
    const val BACKUP = "settings/backup"

    fun editCustomer(customerId: String) = "customers/$customerId/edit"
    fun customerLedger(customerId: String) = "customers/$customerId/ledger"
    fun editProduct(productId: String) = "products/$productId/edit"
    fun productDetail(productId: String) = "products/$productId/detail"
    fun stockAdjust(productId: String) = "products/$productId/stock-adjust"
    fun createInvoice(customerId: String? = null) =
        if (customerId != null) "billing/create/$customerId" else "billing/create"
    fun invoiceDetail(invoiceId: String) = "invoices/$invoiceId"
    fun editInvoice(invoiceId: String) = "invoices/$invoiceId/edit"
    fun invoiceShare(invoiceId: String) = "invoices/$invoiceId/share"
    fun invoicePreview(invoiceId: String) = "invoices/$invoiceId/preview"
    fun editPermissions(userId: String, currentName: String) = "staff/$userId/payments/$currentName"
    fun recordPaymentForInvoice(invoiceId: String) = "payments/record/$invoiceId"

    const val RAZORPAY_CHECKOUT = "razorpay_checkout/{amount}/{invoiceNo}/{customerName}/{razorpayKeyId}"

    fun razorpayCheckout(amount: Double, invoiceNo: String?, customerName: String, razorpayKeyId: String): String {
        return "razorpay_checkout/$amount/${invoiceNo ?: "none"}/${java.net.URLEncoder.encode(customerName, "UTF-8")}/$razorpayKeyId"
    }
}
